language: python
python:
- '2.7'
- '3.5'
install:
- python setup.py install
script:
- python pypower/t/test_pypower.py
deploy:
  provider: pypi
  user: rwl
  password:
    secure: FbT9dTKbWz+AelpZy6Lg/ODkHmFZ1rlZMLnzigLPqBbH+gG7gcLJJno1/qzsLjWlhQVPlSkMSAhfMfTL8Z9j3TtCo8+mSxbUc6ZmmViLU4YNj52uXyq/AlhnR6ALDdkobHEwN0WX2DWcPPx86Vl9+t2EaT9JqbMY7vYrWGtGeYY=
  distributions: sdist
  on:
    tags: true
    repo: rwl/PYPOWER
    branch: master
    python: '2.7'
