language: python
python:
    - "2.7"
    - "3.5"
install:
    - "pip install -e .[dev,build]"
    - pip install codecov pytest-cov
script:
    - pytest --cov=PYPOWER
after_success:
    - codecov
deploy:
  provider: pypi
  user: rwl
  password:
    secure:
  distributions: "sdist"
  on:
    tags: true
    repo: rwl/PYPOWER
    branch: master
    python: "2.7"
